apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-deployment
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: kanban
  template:
    metadata:
      labels:
        app: kanban
    spec:
      containers:
        - name: kanban
          image: necromancerthedark/kanban_image
          ports:
            - containerPort: 80